"""initial schema

Revision ID: 64bf42056595
Revises: 
Create Date: 2026-10-09 16:57:00.492220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid


def _new_id() -> str:
    return str(uuid.uuid4())


revision: str = '64bf42056595'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_badges_slug'), 'badges', ['slug'], unique=True)
    op.create_table('skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_slug'), 'skills', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('daily_activity',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('sessions_count', sa.Integer(), nullable=False),
    sa.Column('messages_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', name='uq_activity_user_day')
    )
    op.create_index(op.f('ix_daily_activity_day'), 'daily_activity', ['day'], unique=False)
    op.create_index(op.f('ix_daily_activity_user_id'), 'daily_activity', ['user_id'], unique=False)
    op.create_table('doc_simplifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('example', sa.Text(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doc_simplifications_user_id'), 'doc_simplifications', ['user_id'], unique=False)
    op.create_table('learning_paths',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_paths_user_id'), 'learning_paths', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('guest_token', sa.String(length=36), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('understanding_score', sa.Integer(), nullable=False),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('solved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_guest_token'), 'sessions', ['guest_token'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('skill_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('encounters', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_id', name='uq_progress_user_skill')
    )
    op.create_index(op.f('ix_skill_progress_user_id'), 'skill_progress', ['user_id'], unique=False)
    op.create_table('user_badges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('badge_id', sa.String(length=36), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_id', name='uq_user_badge')
    )
    op.create_index(op.f('ix_user_badges_user_id'), 'user_badges', ['user_id'], unique=False)
    op.create_table('hints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hints_session_id'), 'hints', ['session_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.create_table('misconceptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_misconceptions_session_id'), 'misconceptions', ['session_id'], unique=False)
    op.create_index(op.f('ix_misconceptions_type'), 'misconceptions', ['type'], unique=False)
    op.create_index(op.f('ix_misconceptions_user_id'), 'misconceptions', ['user_id'], unique=False)
    op.create_table('path_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('path_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['learning_paths.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_path_items_path_id'), 'path_items', ['path_id'], unique=False)
    # ### end Alembic commands ###

    # Seed reference data: badges and skills.
    badges_table = sa.table(
        "badges",
        sa.column("id", sa.String),
        sa.column("slug", sa.String),
        sa.column("name", sa.String),
        sa.column("description", sa.Text),
        sa.column("icon", sa.String),
    )
    op.bulk_insert(
        badges_table,
        [
            {"id": _new_id(), "slug": "first-session", "name": "First Session", "description": "Started your first debugging session.", "icon": "flag"},
            {"id": _new_id(), "slug": "first-solve", "name": "First Solve", "description": "Explained your first fix in your own words.", "icon": "check"},
            {"id": _new_id(), "slug": "hint-free-solve", "name": "No Hints Needed", "description": "Solved a session without spending a single hint.", "icon": "lightbulb"},
            {"id": _new_id(), "slug": "streak-3", "name": "Three-Day Streak", "description": "Practised three days in a row.", "icon": "flame"},
            {"id": _new_id(), "slug": "polyglot", "name": "Polyglot", "description": "Debugged in more than one language.", "icon": "languages"},
            {"id": _new_id(), "slug": "scholar-5", "name": "Scholar", "description": "Solved five debugging sessions.", "icon": "graduation-cap"},
        ],
    )
    skills_table = sa.table(
        "skills",
        sa.column("id", sa.String),
        sa.column("slug", sa.String),
        sa.column("name", sa.String),
        sa.column("description", sa.Text),
    )
    op.bulk_insert(
        skills_table,
        [
            {"id": _new_id(), "slug": "edge-cases", "name": "Edge Cases", "description": "Empty inputs, boundaries and unusual values."},
            {"id": _new_id(), "slug": "loop-logic", "name": "Loop Logic", "description": "Bounds, indexes and off-by-one reasoning."},
            {"id": _new_id(), "slug": "error-handling", "name": "Error Handling", "description": "Crashes, exceptions and defensive checks."},
            {"id": _new_id(), "slug": "testing-habits", "name": "Testing Habits", "description": "Reproducing bugs and verifying fixes."},
            {"id": _new_id(), "slug": "reading-code", "name": "Reading Code", "description": "Tracing execution and naming what code really does."},
            {"id": _new_id(), "slug": "debugging-workflow", "name": "Debugging Workflow", "description": "A systematic approach to finding root causes."},
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_path_items_path_id'), table_name='path_items')
    op.drop_table('path_items')
    op.drop_index(op.f('ix_misconceptions_user_id'), table_name='misconceptions')
    op.drop_index(op.f('ix_misconceptions_type'), table_name='misconceptions')
    op.drop_index(op.f('ix_misconceptions_session_id'), table_name='misconceptions')
    op.drop_table('misconceptions')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_hints_session_id'), table_name='hints')
    op.drop_table('hints')
    op.drop_index(op.f('ix_user_badges_user_id'), table_name='user_badges')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_skill_progress_user_id'), table_name='skill_progress')
    op.drop_table('skill_progress')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_guest_token'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_learning_paths_user_id'), table_name='learning_paths')
    op.drop_table('learning_paths')
    op.drop_index(op.f('ix_doc_simplifications_user_id'), table_name='doc_simplifications')
    op.drop_table('doc_simplifications')
    op.drop_index(op.f('ix_daily_activity_user_id'), table_name='daily_activity')
    op.drop_index(op.f('ix_daily_activity_day'), table_name='daily_activity')
    op.drop_table('daily_activity')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_slug'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_badges_slug'), table_name='badges')
    op.drop_table('badges')
    # ### end Alembic commands ###
