import { Reveal } from "../components/Reveal";

export function Privacy() {
  return (
    <main className="mx-auto w-[min(760px,92%)] py-14 md:py-20">
      <Reveal>
        <p className="eyebrow">Privacy Policy</p>
        <h1 className="mt-3 text-3xl font-extrabold tracking-tight">Your data stays yours</h1>
        <div className="prose-custom mt-6 flex flex-col gap-4 text-[15px] leading-relaxed text-(--muted)">
          <p>
            CodeMentor AI stores your account (email and display name), your debugging
            sessions and messages, and derived progress data such as misconceptions,
            badges, and streaks. This data exists to power your learning path and
            dashboard.
          </p>
          <p>
            Your code snippets are sent to the configured AI provider solely to
            generate mentor replies. API keys are held server-side, never logged,
            and never exposed to the browser.
          </p>
          <p>
            You can delete your account and all associated data at any time. There
            is no advertising profile, no sale of personal data, and no third-party
            tracking on this site.
          </p>
        </div>
      </Reveal>
    </main>
  );
}

export function Terms() {
  return (
    <main className="mx-auto w-[min(760px,92%)] py-14 md:py-20">
      <Reveal>
        <p className="eyebrow">Terms of Service</p>
        <h1 className="mt-3 text-3xl font-extrabold tracking-tight">Fair use, honestly</h1>
        <div className="prose-custom mt-6 flex flex-col gap-4 text-[15px] leading-relaxed text-(--muted)">
          <p>
            CodeMentor AI is a learning tool. Guest mode includes one free debugging
            session; accounts include unlimited sessions subject to fair-use rate
            limits that keep the service fast for everyone.
          </p>
          <p>
            Mentor replies are generated by third-party AI models and may occasionally
            be wrong — that is why the product is built around your own reasoning,
            not the model’s authority. Always test your code before shipping it.
          </p>
          <p>
            Do not use the service to generate disallowed content, attack systems, or
            abuse the API. Accounts that do so may be disabled.
          </p>
        </div>
      </Reveal>
    </main>
  );
}
